plugins:
  # - '@shopify/prettier-plugin-liquid'
  - 'prettier-plugin-jinja-template'

trailingComma: es5
singleQuote: true

overrides:
  - files:
      - '*.html'
      - '*.njk'
    options:
      # use jinja-template as an "almost nunjucks" one...
      parser: jinja-template
      singleQuote: false
      printWidth: 80
