plugins:
  - '@shopify/prettier-plugin-liquid'

trailingComma: es5
singleQuote: true
editorConfig: true

overrides:
  - files:
      - '*.html'
      - '*.njk'
    options:
      # use liquid parser as an "almost nunjucks" one...
      parser: liquid-html
      singleQuote: false
      printWidth: 80
